version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_USER: user
      DB_NAME: db
      DB_HOST: postgres
      DB_PASS: pass
    ports:
      - "5000:5000"
    command: npm run start

